name: eye_speak_mobile
description: Flutter mobile implementation of EyeSpeak Assist.
version: 0.1.0

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.3.0
  camera: ^0.10.5
  flutter_tts: ^3.6.3

flutter:
  uses-material-design: true
  assets:
    - assets/phrases.json
